name: My First Action

on: 
  push:

jobs:
  react_on_push:
      runs-on: ubuntu-latest
      steps:
      - name: discord
        uses: sebastianpopp/discord-action@releases/v2 
        with: 
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: ${{ github.actor}} has  successfullly published to main.
